#!/bin/bash
args=`echo $@`

head -n 16 configure.ac | grep VERSION= > /tmp/commitTool.tmp
source /tmp/commitTool.tmp
EXTRA_VERSION=`echo $EXTRA_VERSION | awk -F'.' '{for (i=1;i<NF;i++){printf $i"."};printf $NF+1}'`
nextsversion="${MAJOR_VERSION}.${MINOR_VERSION}.${MICRO_VERSION}cvs${EXTRA_VERSION}"
nextextra="$EXTRA_VERSION"
nextextratype="head"
rm /tmp/commitTool.tmp

IFS='
'
filelist=`cvs status $@ configure.ac 2>/dev/null |grep ^File`

for file in $filelist; do
	merge=`echo $file | grep Merge`
	modif=`echo $file | grep Locally`
	patch=`echo $file | grep -i patch`
	if [ "$patch" != "" ]; then
		echo $patch 
		echo You have to update first
		exit
	fi;
	if [ "$merge" != "" ]; then
		echo $merge 
		echo You have to update first
		exit
	fi;
	if [ "$modif" != "" ]; then
		echo $modif
	fi;
done;
patchset="("
log=""
files=`cvs diff -uN $@ 2>/dev/null |grep ^Index`
name=`whoami`
#change if your login isn't your name
if [ "$name" == "claws" ]; then
	name="paul";
fi;
if [ "$name" == "reboot" ]; then
	name="christoph";
fi;
if [ "$name" == "leroyc" ]; then
	name="colin";
fi;
if [ "$name" == "torte" ]; then
	name="thorsten";
fi;

log="`date --utc +%Y-%m-%d` [$name]\t$nextsversion\n\n"
for line in $files; do
	file=`echo $line | cut -d' ' -f2`
	dir=`dirname $file`
	filename=`basename $file`
	cvsfile="$dir/CVS/Entries"
	version=`grep "\/$filename\/" $cvsfile | cut -d'/' -f3`
	nextversion=`echo $version | awk -F'.' '{for (i=1;i<NF;i++){printf $i"."};printf $NF+1}'`
	
	log="$log\t* $file\n"
	patchset="$patchset cvs diff -u -r $version -r $nextversion $file;\
"
done;
patchset="$patchset ) > $nextsversion.patchset"

if [ "$EDITOR" == "" ]; then
	EDITOR=vi
fi;


echo -e "#please complete the changelog entry below" > /tmp/logentry
echo -e -n $log >> /tmp/logentry

$EDITOR /tmp/logentry

echo "--8<----------"
grep -v "^#" /tmp/logentry > /tmp/log.tmp.$$ \
&& mv /tmp/log.tmp.$$ /tmp/logentry
echo >> /tmp/logentry
cat /tmp/logentry

echo "--8<----------"
if [ -f ChangeLog-gtk2.claws ]; then
	chlog="ChangeLog-gtk2.claws"
elif [ -f ChangeLog.claws ]; then
	chlog="ChangeLog.claws"
else
	chlog="ChangeLog"
fi
echo -n "Is it ok (write to $chlog and update configure.ac) [y/N]?"
read ans
if [ "$ans" == "y" ]; then
	mv $chlog $chlog.old
	cat /tmp/logentry > $chlog
	cat $chlog.old >> $chlog
	rm $chlog.old

	cat configure.ac | sed "s/^EXTRA_VERSION=.*/EXTRA_VERSION=$nextextra/" > configure.ac.new \
	&& mv configure.ac.new configure.ac ;
	
	echo "$patchset" >> PATCHSETS

	if [ "$args" != "" ]; then
		echo commiting $@ PATCHSETS $chlog configure.ac
		cvs commit -m "`cat /tmp/logentry`" $@ PATCHSETS $chlog configure.ac
	else
		echo commiting recursively
		cvs commit -m "`cat /tmp/logentry` "
	fi;
	rm -f /tmp/logentry
fi
