static char *AUTHORS_LIST =
"Hiroyuki Yamamoto\n"
"Hoa viet Dinh\n"
"Keith Edmunds \n"
"Match Grun\n"
"Melvin Hadasht\n"
"Oliver Haertel \n"
"Christoph Hohmann\n"
"Alfons Hoogervorst\n"
"Darko Koruga\n"
"Colin Leroy\n"
"Paul Mangan\n"
"Leandro A. F. Pereira \n"
"Luke Plant \n"
"Martin Schaaf\n"
"Carsten Schurig\n"
"Sergey Vlasov\n"
"Werner Koch\n"
"Thorsten Maerz\n"
"George Danchev \n"
"Miquel Oliete \n"
"Thomas Gilgin \n"
"Ricardo Mones Lastra \n"
"Flammie Pirinen \n"
"Fabien Vantard \n"
"Dragan \n"
"Andrea Spadaccini \n"
"Rui Hirokawa \n"
"SungHyun Nam \n"
"Geir Helland \n"
"Emilian Nowak\n"
"Frederico Goncalves Guimaraes \n"
"Pavlo Bohmat \n"
"Andrej Kacian \n"
"Urke MMI \n"
"Hansom Young \n"
"Wei-Lun Chao \n"
"François Barriere \n"
"Martin Bretschneider\n"
"Paul Kater\n"
"Jens Oberender\n"
"Marcelo Ramos \n"
"Guido Rudolphi\n"
"Nick Selby\n"
"Yoichi Imai (Japanese)\n"
"Paul Kater (English)\n"
"WAKAI Kazunao\n"
"Jakub 'jimmac' Steiner\n"
"Aleksandar Urosevic\n"
"Jesper Schultz\n"
"Alte\n"
"Pierric Descamps\n"
"Ohmasa\n"
"Stephen Anthony\n"
"HIRAMATSU Masami\n"
"Jorge Van Hemelryck\n"
"TAKANO\n"
"Masahiro Tomita\n"
"Mathias Intemann\n"
"Chideok Hwang\n"
"Marc Hoper\n"
"David Mehrmann\n"
"Setoh\n"
"Yuuki NINOMIYA\n"
"Suzuki Mio\n"
"Ishihara\n"
"Jason McCarver\n"
"Sakamoto\n"
"Hiramatu\n"
"John E.P. Hynes\n"
"Maki\n"
"Takahashi\n"
"Nishimura\n"
"Yoichi Imai\n"
"Tsutsui\n"
"Yanase\n"
"TOGAWA\n"
"Higuchi\n"
"Paul Rolland\n"
"KUROSAWA\n"
"NAKAGAWA\n"
"HIROSHIMA\n"
"Tanaka\n"
"Hashimoto\n"
"T. Yamamoto\n"
"YAMAGUCHI\n"
"Tomita\n"
"Nishiyama\n"
"Michihide Hotta\n"
"Nishika\n"
"shigeri\n"
"Tajiri\n"
"Rodrigo Dias Arruda Senra\n"
"Fabio Junior Beneditto\n"
"Satoshi Nagayasu\n"
"Henrik Carlqvist\n"
"Don Quijote\n"
"David Looney\n"
"Eric Limpens\n"
"Paul Evans\n"
"wwp\n"
"Jeroen Versteeg\n"
"Ravemax\n"
"Jens Jahnke\n"
"Thierry Godefroy\n"
"Matthieu Dazy\n"
"Jonathan Ware\n"
"Yasumatsu\n"
"Stefaan A Eeckels\n"
"OSHIRO Naoki\n"
"KAJIWARA\n"
"Hironori IWANE\n"
"Manrat Chobchuen\n"
"Shimamoto 'Neko' Tatsuya\n"
"Jesse Skinner\n"
"Willem van Engen\n"
"Tobias Sandhaas\n"
"Thomas Link\n"
"Martin Pool\n"
"Fredrik Olofssen\n"
"Gustavo Noronha Silva\n"
"Simon 'corecode' Schubert\n"
"Dale P. Smith\n"
"Yukihiro Nakai\n"
"Watanabe\n"
"Masaaki Noro\n"
"Motonobu Ichimura\n"
"Luca Rosellini\n"
"Yasuzaki Masayoshi\n"
"Stoyan Genov\n"
"Jeremy Andrews\n"
"Shawn Houston\n"
"Alessandro Maestri\n"
"Neill Miller\n"
"Oliver Haertel\n"
"Bob Forsman\n"
"Ville Skyttä\n"
"Wilbert Berendsen\n"
"Bob Woodside\n"
"Stefaan Eeckels\n"
"Pascal Jermini\n"
"Thorsten Thielen\n"
"Eugene Brevdo\n"
"Mitko Haralanov\n"
"Bram Metsch\n"
"Stanislav Karchebny\n"
"Torsten Schoenfeld\n"
"Xavier FACQ\n"
"Botalov Vyacheslav\n"
"Urosevic Aleksandar\n"
"Martin Kluge\n"
"George Danchev\n"
"Ruslan N. Balkin\n"
"Nicolas Kaiser\n"
"Ivan Francolin Martinez\n"
"Topia\n"
"Gál Zoltán\n"
"Mohammed Sameer\n"
"Kim Schulz\n"
"Christian Mertes\n"
"Jens Rantil\n"
"Florian Mickler\n"
"André Filipe de Assunção e Brito\n"
"Sergei Astanin\n"
"Kevin Vigor\n"
"James Noyes\n"
"Radek Vybiral\n"
"Tsu-Fan Cheng\n"
"Martin Zwickel\n"
"Martin Wicke\n"
"Pawel Pêkala\n"
"Bogdan Sumanariu\n"
"David Relson\n"
"Matthias Förste\n"
"David Chalmers\n"
"Chad Robinson\n"
"Edgar Toernig\n"
"Fabien Vantard\n"
"Reza Pakdel\n"
"Stephan Sachse\n"
"Thomas Gilgin\n"
"Guy Rouillier\n"
"Jean-Yves Lefort\n"
"George Michaelson\n"
"IWAMOTO Kouichi\n"
"Alex S Moore\n"
"Felix Eckhofer\n"
"Rich Coe\n"
"Ivan Rayner\n"
"Markus Schwarzenberg\n"
"Luca Cavalli\n"
"Tim Mann\n"
"M. Benkmann\n"
"Yang Guilong\n"
"Daniel Gustafson\n"
"Anders Hammar\n"
"Andrew Nelson\n";
